### PR TITLE
[title] -> [main-title]

### PR DESCRIPTION
**Pull request by blasten**

### CODE REVIEW

**Comment by keanulee** [comment]
(Brainstorming for better names, feel free to discuss)

Reading the description of app-header's `condenses` property, it might be clearer if we renamed some things:

```
/s/condenses/collapses/
/s/condensed-title/collapsed-title/
/s/main-title/expanded-title/
/s/primary/pinned/
```

WDYT @blasten @frankiefu ?

**Comment by blasten** [comment]
I don't have strong opinion, but I do agree that if we want to make attribute name changes, we should do them along with this one. I thought about renaming `primary` as `sticky` because the behavior is similar to `position:sticky;`

**Comment by frankiefu** [comment]
`pinned` is better than `primary`.  But I think `sticky` is better given `position: sticky`.  I don't have strong opinion on `/s/condenses/collapses/`.  I do think we should keep `main-title` since we use that even when there is only one title: https://github.com/PolymerElements/app-layout/blob/main-title/app-toolbar/demo/index.html#L66

**Comment by frankiefu** [comment]
A few places are still using `title`:
https://github.com/PolymerElements/app-layout/blob/main-title/app-header/app-header.html#L155
https://github.com/PolymerElements/app-layout/blob/main-title/app-header/README.md#L145
https://github.com/PolymerElements/app-layout/blob/main-title/demo/demo1.html#L82

**Pull request merged**
