### PR TITLE
Fix stacking context of 'shadow'

### LINKED ISSUE #392: Small stacking-context problem in app-header [shadow]
### Description
Whenever an app-header is using `shadow` and the app-header's content uses something like a `paper-menu-button` to display a dropdown menu, the app-header's shadow is "above" the menu content.

### Expected outcome
Toolbar content should be above the app-header's shadow

### Actual outcome
Toolbar content is below the app-header's shadow

app-header

### Live Demo
https://jsbin.com/jelopim/edit?html,output

### Steps to reproduce
1. Create a setup similar to the following
```
<app-header-layout>
  <app-header shadow>
    <app-toolbar>
      <paper-menu-button>...</paper-menu-button>
    </app-toolbar>
  </app-header>
  <div content></div>
</app-header-layout>
```
2. Open the page in a web browser.
3. Expand the paper-menu-button

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

### PR DESCRIPTION
**Pull request by robrez**
Fixes #392 by creating an appropriate stacking context between an app-header's content and its shadow

### CODE REVIEW

**Comment by blasten** [comment]
@robrez I think you can also fix the issue by setting `z-index: -1;`  in `:host:after`. It seems to work in Chrome, Safari, Firefox and Edge.

**Comment by keanulee** [comment]
Creating a new element just for the shadow (which may not even be used in some cases) seems expensive. Would it be possible to use `::before` instead (so it's lower on the stack)?

**Comment by blasten** [comment]
^ or that. `::before` will also do it.

**Comment by robrez** [comment]
Thanks for the help.  I've updated the PR to use `::before` as suggested.

**Comment by blasten** [comment]
Thanks!

**Pull request merged**
