### PR TITLE
add padding var

### PR DESCRIPTION
**Pull request by 43081j**
what do you think of this? we have a problem at the min where we can't pass a mixin in because `@apply` isn't supported on our end. so we can't get rid of/change the default padding of the drawer.

would this work? let me know what you think

cc @aomarks

### CODE REVIEW

**Comment by 43081j** [comment]
Thanks for taking a look. 

Will add the docs in the morning 👍

**Comment by 43081j** [comment]
here you go, let me know if you want me to add anything else

**Comment by e111077** [comment]
release awaiting internal testing

**Comment by e111077** [comment]
published under 3.1.0

**Pull request merged**
