### PR TITLE
Added event to app-header for the scroll state change.

### PR DESCRIPTION
**Pull request by BAGELreflex**
Needed to hook into the scroll state changing for the app-header in order to show/hide other elements on the page respectively.

Added details for progress and top values of the scroll state change in order to animate corresponding elements.

### CODE REVIEW

**Comment by BAGELreflex** [comment]
I signed it!

**Comment by blasten** [comment]
There's a way to achieve this behavior without firing an event from app-header: https://github.com/PolymerElements/app-layout/blob/master/app-header/demo/music.html#L199-L204

I'll close this PR in favor of the existing approach, please open an issue if you find a problem.

**Comment by BAGELreflex** [comment]
The provided alternative is in relation to appBox.getScrollState(). I assume it would be equally portable to appHeader.getScrollState(). My concern would be that this listener is listening to the window's scroll event, meaning that it attempts to handle the event way more often that would be needed. The handler would fire, the logic would run, it would be found that nothing needs to happen, and it would continue propagating the event, every single time the scroll event first.

The provided solution in the pull request limits the need for logical checks to the short transition of appHeader to appHeader.condensed, by adding a single line.

Is unnecessary logic checking really the Polymeric way to handle this, vs an event that has a short life-span, and would prove quite useful in multiple situations?

Use case: http://i.imgur.com/ItqmZjq.gifv

**Comment by blasten** [comment]
Yes, app-header also has `getScrollState`.  You can short-circuit it by keeping track of the previous `progress` value that comes out of `getScrollState`. Firing an event from the scroll event is not cheap, even if the event doesn't bubble, there's some cost that can be avoided since most folks won't be using that custom event.

**Pull request closed without merging**
