### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mdwragg**
Add Predix Design System to list of users ;)

### CODE REVIEW

**Comment by mdwragg** [comment]
I signed it

**Comment by TimvdLippe** [comment]
Closing per above comment. Sadly we can't accept this PR without a CLA.

**Comment by mdwragg** [comment]
Weird, I already signed it :-(

**Comment by TimvdLippe** [comment]
Hm, maybe open a new PR to fix the CLA issue?

**Pull request closed without merging**
