### PR TITLE
2.0 preview master

### PR DESCRIPTION
**Pull request by blasten**

### CODE REVIEW

**Comment by keanulee** [comment]
Hmm, seems like you merged from an older head of `master` branch (commit 0d8311c), which doesn't include the more recent changes (like app-drawer no longer using transitionend). Did you have to resolve any conflicts? If so, we should merge this so that there's less to resolve when we merge the more recent commits to `master`. Otherwise, I would merge a more recent commit of `master` (`git checkout master; git pull; git checkout 2.0-preview; git merge master`)

**Comment by frankiefu** [comment]
The `app-grid` tests are failing.

**Comment by blasten** [comment]
@keanulee fyi, the app-drawer tests are still failing. It seems like some of the changes from master are causing the issues. You probably are more familiar with those changes. Juts look at these two builds:
* 2.0-preview: https://travis-ci.org/PolymerElements/app-layout/builds/207216544
* After master merging into 2.0-preview: https://travis-ci.org/PolymerElements/app-layout/builds/207565233

**Comment by frankiefu** [comment]
Those failing tests are trying to check the transition duration after a fling.  Took a quick look at the code and seems like the velocity used to calculate the duration could be different if running on a slower machine.  I can reproduce the failures running those tests on Chrome with CPU Throttling set to `20x`.

**Comment by frankiefu** [comment]
LGTM 💯

**Pull request merged**
